use PCGD
go
CREATE TABLE ChuongTrinh
(
	ID INT NOT NULL IDENTITY(1,1),
	NgayTao DATETIME NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Khoa
(
	ID INT NOT NULL IDENTITY(1,1),
	TenKhoa NVARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Nganh
(
	ID INT NOT NULL IDENTITY(1,1),
	Khoa_ID INT NOT NULL,
	TenNganh NVARCHAR(255) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (Khoa_ID) REFERENCES Khoa(ID) ON DELETE CASCADE
);

CREATE TABLE Lop
(
	MaLop CHAR(6) NOT NULL,
	Nganh_ID INT NOT NULL,
	ChuongTrinh_ID INT NOT NULL,
	SoSV INT NOT NULL,
	PRIMARY KEY (MaLop),
	FOREIGN KEY (Nganh_ID) REFERENCES Nganh(ID) ON DELETE CASCADE,
	FOREIGN KEY (ChuongTrinh_ID) REFERENCES ChuongTrinh(ID) ON DELETE CASCADE,
);

CREATE TABLE HocPhan
(
	MaHP CHAR(6) NOT NULL,
	TenHP NVARCHAR(255) NOT NULL,
	SoTC INT NOT NULL,
	SoTCBatBuoc INT,
	SoTCTuChon INT,
	SoTietLT INT,
	SoTietTH INT,
	PRIMARY KEY (MaHP)
);

CREATE TABLE ChuongTrinh_HocPhan
(
	ChuongTrinh_ID INT NOT NULL,
	MaHP CHAR(6) NOT NULL,
	FOREIGN KEY (ChuongTrinh_ID) REFERENCES ChuongTrinh(ID) ON DELETE CASCADE,
	FOREIGN KEY (MaHP) REFERENCES HocPhan(MaHP) ON DELETE CASCADE
);

CREATE TABLE GiangVien
(
	ID INT NOT NULL IDENTITY(1,1),
	TenGV NVARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE GiangVien_HocPhan
(
	GiangVien_ID INT NOT NULL,
	MaHP CHAR(6) NOT NULL,
	FOREIGN KEY (GiangVien_ID) REFERENCES GiangVien(ID) ON DELETE CASCADE,
	FOREIGN KEY (MaHP) REFERENCES HocPhan(MaHP) ON DELETE CASCADE
);

CREATE TABLE HocKi
(
	ID INT NOT NULL IDENTITY(1,1),
	HocKi TINYINT NOT NULL,
	NgayTao DATETIME NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE TaiKhoan
(
	ID INT NOT NULL IDENTITY(1,1),
	TaiKhoan NVARCHAR(100) NOT NULL,
	MatKhau CHAR(255) NOT NULL,
	NgayTao DATETIME NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PhanCong
(
	ID INT NOT NULL IDENTITY(1,1),
	TaiKhoan_ID INT NOT NULL,
	HocKi_ID INT NOT NULL,
	MaHP CHAR(6) NOT NULL,
	MaLop CHAR(6) NOT NULL,
	GiangVien_ID INT NOT NULL,
	GhiChu NVARCHAR(255) NOT NULL,
	LoaiPhong char(2),
	NhomLT INT,
	NhomHT INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (TaiKhoan_ID) REFERENCES TaiKhoan(ID) ON DELETE CASCADE,
	FOREIGN KEY (HocKi_ID) REFERENCES HocKi(ID) ON DELETE CASCADE,
	FOREIGN KEY (MaHP) REFERENCES HocPhan(MaHP) ON DELETE CASCADE,
	FOREIGN KEY (MaLop) REFERENCES Lop(MaLop) ON DELETE CASCADE,
	FOREIGN KEY (GiangVien_ID) REFERENCES GiangVien(ID) ON DELETE CASCADE
);

DROP TABLE PhanCong;
DROP TABLE GiangVien;
DROP TABLE HocPhan;
DROP TABLE Lop;
DROP TABLE Nganh;
DROP TABLE ChuongTrinh;
DROP TABLE ChuongTrinh_HocPhan;
DROP TABLE GiangVien_HocPhan;
DROP TABLE TaiKhoan;
DROP TABLE Khoa;
DROP TABLE HocKi;