CREATE TABLE ChuongTrinh
(
	ID INT NOT NULL IDENTITY(1,1),
	NgayTao DATETIME NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE HocPhan
(
	MaHP CHAR(6) NOT NULL,
	ChuongTrinh_ID INT NOT NULL,
	TenHP NVARCHAR(255) NOT NULL,
	SoTC INT NOT NULL,
	SoTCBatBuoc INT,
	SoTCTuChon INT,
	SoTietLT INT,
	SoTietTH INT,
	PRIMARY KEY (MaHP),
	FOREIGN KEY (ChuongTrinh_ID) REFERENCES ChuongTrinh(ID) ON DELETE CASCADE
);

CREATE TABLE Nganh
(
	ID INT NOT NULL IDENTITY(1,1),
	TenNganh NVARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Khoa
(
	MaKhoa CHAR(4) NOT NULL,
	Nganh_ID INT NOT NULL,
	ChuongTrinh_ID INT NOT NULL,
	SoSV INT NOT NULL,
	PRIMARY KEY (MaKhoa),
	FOREIGN KEY (Nganh_ID) REFERENCES Nganh(ID) ON DELETE CASCADE,
	FOREIGN KEY (ChuongTrinh_ID) REFERENCES ChuongTrinh(ID) ON DELETE CASCADE,
);

CREATE TABLE GiangVien
(
	ID INT NOT NULL IDENTITY(1,1),
	TenGV NVARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE GhiChu
(
	ID INT NOT NULL IDENTITY(1,1),
	NoiDung NVARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PhanCong
(
	ID INT NOT NULL IDENTITY(1,1),
	MaHP CHAR(6) NOT NULL,
	GiangVien_ID INT NOT NULL,
	GhiChu_ID INT NOT NULL,
	LoaiPhong char(2),
	NhomLT INT,
	NhomHT INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (MaHP) REFERENCES HocPhan(MaHP) ON DELETE CASCADE,
	FOREIGN KEY (GiangVien_ID) REFERENCES GiangVien(ID) ON DELETE CASCADE,
	FOREIGN KEY (GhiChu_ID) REFERENCES GhiChu(ID) ON DELETE CASCADE
);

DROP TABLE ChuongTrinh;
DROP TABLE HocPhan;
DROP TABLE Nganh;
DROP TABLE Khoa;
DROP TABLE GiangVien;
DROP TABLE PhanCong;