use PCGD
go
CREATE TABLE ChuongTrinh
(
	ID INT NOT NULL IDENTITY(1,1),
	NgayTao DATETIME NOT NULL UNIQUE,
	PRIMARY KEY (ID)
);

CREATE TABLE Khoa
(
	ID INT NOT NULL IDENTITY(1,1),
	TenKhoa NVARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY (ID)
);

CREATE TABLE Nganh
(
	ID INT NOT NULL IDENTITY(1,1),
	Khoa_ID INT NOT NULL,
	TenNganh NVARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY (ID),
	FOREIGN KEY (Khoa_ID) REFERENCES Khoa(ID) ON DELETE CASCADE
);

CREATE TABLE Lop
(
	ID INT NOT NULL IDENTITY(1,1),
	MaLop CHAR(6) NOT NULL UNIQUE,
	Nganh_ID INT NOT NULL,
	ChuongTrinh_ID INT NOT NULL,
	SoSV INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (Nganh_ID) REFERENCES Nganh(ID) ON DELETE CASCADE,
	FOREIGN KEY (ChuongTrinh_ID) REFERENCES ChuongTrinh(ID) ON DELETE CASCADE,
);

CREATE TABLE HocPhan
(
	ID INT NOT NULL IDENTITY(1,1),
	MaHP CHAR(6) NOT NULL UNIQUE,
	TenHP NVARCHAR(255) NOT NULL,
	HocKi TINYINT NOT NULL,
	SoTC INT NOT NULL,
	SoTCBatBuoc INT,
	SoTCTuChon INT,
	SoTietLT INT,
	SoTietTH INT,
	PRIMARY KEY (ID)
);

CREATE TABLE ChuongTrinh_HocPhan
(
	ID INT NOT NULL IDENTITY(1,1),
	ChuongTrinh_ID INT NOT NULL,
	HocPhan_ID INT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (ChuongTrinh_ID) REFERENCES ChuongTrinh(ID) ON DELETE CASCADE,
	FOREIGN KEY (HocPhan_ID) REFERENCES HocPhan(ID) ON DELETE CASCADE
);

CREATE TABLE GiangVien
(
	ID INT NOT NULL IDENTITY(1,1),
	TenGV NVARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE GiangVien_HocPhan
(
	ID INT NOT NULL IDENTITY(1,1),
	GiangVien_ID INT NOT NULL,
	HocPhan_ID INT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (GiangVien_ID) REFERENCES GiangVien(ID) ON DELETE CASCADE,
	FOREIGN KEY (HocPhan_ID) REFERENCES HocPhan(ID) ON DELETE CASCADE
);

CREATE TABLE TaiKhoan
(
	ID INT NOT NULL IDENTITY(1,1),
	QuyenHan TINYINT NOT NULL,
	TaiKhoan NVARCHAR(100) NOT NULL,
	MatKhau CHAR(255) NOT NULL,
	NgayTao DATETIME NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PhanCong
(
	ID INT NOT NULL IDENTITY(1,1),
	TaiKhoan_ID INT NOT NULL,
	HocKi TINYINT NOT NULL,
	NgayTao DATETIME NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (TaiKhoan_ID) REFERENCES TaiKhoan(ID) ON DELETE CASCADE
);

CREATE TABLE NhiemVu
(
	ID INT NOT NULL IDENTITY(1,1),
	Lop_ID INT NOT NULL,
	PhanCong_ID INT NOT NULL,
	HocPhan_ID INT NOT NULL,
	GiangVien_ID INT NOT NULL,
	GhiChu NVARCHAR(255) NOT NULL,
	LoaiPhong char(2),
	NhomLT INT,
	NhomHT INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (Lop_ID) REFERENCES Lop(ID) ON DELETE CASCADE,
	FOREIGN KEY (PhanCong_ID) REFERENCES PhanCong(ID) ON DELETE CASCADE,
	FOREIGN KEY (HocPhan_ID) REFERENCES HocPhan(ID) ON DELETE CASCADE,
	FOREIGN KEY (GiangVien_ID) REFERENCES GiangVien(ID) ON DELETE CASCADE
);

DROP TABLE ChuongTrinh_HocPhan;
DROP TABLE PhanCong;
DROP TABLE Lop;
DROP TABLE ChuongTrinh;
DROP TABLE Nganh;
DROP TABLE Khoa;
DROP TABLE GiangVien_HocPhan;
DROP TABLE HocPhan;
DROP TABLE GiangVien;
DROP TABLE TaiKhoan;