//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCGD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NhiemVu
    {
        public long ID { get; set; }

        [Display(Name = "Lớp")]
        [Required(ErrorMessage = "Lớp không được bỏ trống!")]
        public long Lop_ID { get; set; }

        public long PhanCong_ID { get; set; }

        [Display(Name = "Học phần")]
        [Required(ErrorMessage = "Học phần không được bỏ trống!")]
        public long HocPhan_ID { get; set; }

        [Display(Name = "Giảng viên")]
        [Required(ErrorMessage = "Giảng viên không được bỏ trống!")]
        public long GiangVien_ID { get; set; }

        [Display(Name = "Loại phòng")]
        [Required(ErrorMessage = "Loại phòng không được bỏ trống!")]
        [Range(0, 1, ErrorMessage = "Loại phòng không hợp lệ!")]
        public byte LoaiPhong { get; set; }

        [Display(Name = "Nhóm lý thuyết")]
        public Nullable<int> NhomLT { get; set; }

        [Display(Name = "Nhóm thực hành")]
        public Nullable<int> NhomHT { get; set; }

        [Display(Name = "Ghi chú")]
        [StringLength(255, MinimumLength = 0, ErrorMessage = "Vui lòng không nhập ghi chú lớn hơn 255 kí tự!")]
        public string GhiChu { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual HocPhan HocPhan { get; set; }
        public virtual Lop Lop { get; set; }
        public virtual PhanCong PhanCong { get; set; }
    }
}
