//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCGD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ChuongTrinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuongTrinh()
        {
            this.HocKi = new HashSet<HocKi>();
            this.Lop = new HashSet<Lop>();
        }
    
        public int ID { get; set; }

        [Display(Name = "Tên chương trình")]
        [Required(ErrorMessage = "Tên chương trình không được bỏ trống!")]
        public string TenCT { get; set; }

        [Display(Name = "Ngày tạo")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date, ErrorMessage = "Định dạng ngày tạo không hợp lệ")]
        [Required(ErrorMessage = "Ngày tạo không được bỏ trống!")]
        public System.DateTime NgayTao { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HocKi> HocKi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lop> Lop { get; set; }
    }
    public class ViewChuongTrinhModel
    {
        public ChuongTrinh ChuongTrinh { get; set; }
        public IEnumerable<ViewHocKiModel> HocKi { get; set; }
        public IEnumerable<NhomHocPhan> NhomHocPhan { get; set; }
        public IEnumerable<ChiTietHocPhan> ChiTietHocPhan { get; set; }
        public IEnumerable<HocPhan> HocPhan { get; set; }
    }
    public class ViewHocKiModel
    {
        public long ID { get; set; }
        public int ChuongTrinh_ID { get; set; }
        public int SoHocPhan { get; set; }
        public int TongTC { get; set; }
        public int TongTCBatBuoc { get; set; }
        public int TongTCTuChon { get; set; }
        public byte SoHocKi { get; set; }
    }
    public class HocPhanModel
    {
        public long ID { get; set; }
        public long ChiTietHocPhan_ID { get; set; }
        public string MaHP { get; set; }
        public string TenHP { get; set; }
        public byte LoaiHP { get; set; }
        public int SoTC { get; set; }
        public byte HocPhanDieuKien { get; set; }
        public Nullable<int> SoTietLT { get; set; }
        public Nullable<int> SoTietTH { get; set; }
    }
    public class NhomHocPhanModel
    {
        public long NhomHocPhan_ID { get; set; }

        [Display(Name = "Học phần điều kiện")]
        [Required(ErrorMessage = "Học phần điều kiện không được bỏ trống!")]
        [Range(0, 1, ErrorMessage = "Học phần điều kiện không hợp lệ!")]
        public byte HocPhanDieuKien { get; set; }

        [Display(Name = "Học phần thay thế")]
        [Required(ErrorMessage = "Học phần thay thế không được bỏ trống!")]
        [Range(0, 1, ErrorMessage = "Học phần thay thế không hợp lệ!")]
        public byte HocPhanThayThe { get; set; }

        [Display(Name = "Tổng tín chỉ")]
        [Required(ErrorMessage = "Tổng tín chỉ không được bỏ trống!")]
        public int TongTC { get; set; }
    }
    public class ViewNhomHocPhan
    {
        public ChuongTrinh ChuongTrinh { get; set; }
        public NhomHocPhan NhomHocPhan { get; set; }
        public NhomHocPhanModel NhomHocPhanModel { get; set; }
        public IEnumerable<HocPhanModel> HocPhan { get; set; }
    }
    public class ThemHocPhanModel
    {
        public long NhomHocPhan_ID { get; set; }

        [Display(Name = "Mã học phần")]
        [Required(ErrorMessage = "Mã học phần không được bỏ trống!")]
        public string MaHP { get; set; }

        [Display(Name = "Số tiết lý thuyết")]
        public Nullable<int> SoTietLT { get; set; }

        [Display(Name = "Số tiết thực hành")]
        public Nullable<int> SoTietTH { get; set; }
    }
    public class SuaHocPhanModel
    {
        public long NhomHocPhan_ID { get; set; }
        public long ChiTietHocPhan_ID { get; set; }

        [Display(Name = "Mã học phần")]
        [Required(ErrorMessage = "Mã học phần không được bỏ trống!")]
        public string MaHP { get; set; }

        [Display(Name = "Học phần điều kiện")]
        [Required(ErrorMessage = "Học phần điều kiện không được bỏ trống!")]
        [Range(0, 1, ErrorMessage = "Học phần điều kiện không hợp lệ!")]
        public byte HocPhanDieuKien { get; set; }

        [Display(Name = "Số tiết lý thuyết")]
        public Nullable<int> SoTietLT { get; set; }

        [Display(Name = "Số tiết thực hành")]
        public Nullable<int> SoTietTH { get; set; }
    }
    public class XoaHocPhanModel
    {
        public long NhomHocPhan_ID { get; set; }
        public string MaHP { get; set; }
    }
    public class XoaNhomHocPhanModel
    {
        public int ChuongTrinh_ID { get; set; }
        public IEnumerable<HocPhanModel> HocPhan { get; set; }
    }
}
