//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCGD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Lop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lop()
        {
            this.NhiemVu = new HashSet<NhiemVu>();
        }
    
        public long ID { get; set; }

        [Display(Name = "Ngành")]
        [Required(ErrorMessage = "Ngành không được bỏ trống!")]
        public int Nganh_ID { get; set; }

        [Display(Name = "Chương trình")]
        [Required(ErrorMessage = "Chương trình không được bỏ trống!")]
        public int ChuongTrinh_ID { get; set; }

        [Display(Name = "Tên lớp")]
        [Required(ErrorMessage = "Tên lớp không được bỏ trống!")]
        public string TenLop { get; set; }

        [Display(Name = "Số sinh viên")]
        [Required(ErrorMessage = "Số sinh viên không được bỏ trống!")]
        public int SoSV { get; set; }
    
        public virtual ChuongTrinh ChuongTrinh { get; set; }
        public virtual Nganh Nganh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhiemVu> NhiemVu { get; set; }
    }
}
