//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCGD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GiangVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiangVien()
        {
            this.ChiTietGiangVien = new HashSet<ChiTietGiangVien>();
            this.ChiTietTongHop = new HashSet<ChiTietTongHop>();
            this.NhiemVu = new HashSet<NhiemVu>();
        }
    
        public long ID { get; set; }

        [Display(Name = "Tên giảng viên")]
        [Required(ErrorMessage = "Tên giảng viên không được bỏ trống!")]
        public string TenGV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietGiangVien> ChiTietGiangVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTongHop> ChiTietTongHop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhiemVu> NhiemVu { get; set; }
    }
    public class ThemHocPhanGiangVienModel
    {
        public long GiangVien_ID { get; set; }

        [Display(Name = "Mã học phần")]
        [Required(ErrorMessage = "Mã học phần không được bỏ trống!")]
        public string MaHP { get; set; }
    }
    public class SuaHocPhanGiangVienModel
    {
        public long ChiTietGiangVien_ID { get; set; }
        public long GiangVien_ID { get; set; }

        [Display(Name = "Mã học phần")]
        [Required(ErrorMessage = "Mã học phần không được bỏ trống!")]
        public string MaHP { get; set; }
    }
    public class XoaHocPhanGiangVienModel
    {
        public long ChiTietGiangVien_ID { get; set; }
        public long GiangVien_ID { get; set; }
        public string MaHP { get; set; }
    }
    public class HocPhanGiangVienModel
    {
        public long ChiTietGiangVien_ID { get; set; }
        public string MaHP { get; set; }
        public string TenHP { get; set; }
        public byte LoaiHP { get; set; }
        public int SoTC { get; set; }
    }
    public class ViewGiangVienModel
    {
        public long GiangVien_ID { get; set; }
        public IEnumerable<HocPhanGiangVienModel> HocPhan { get; set; }
    }
}
