//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiangVien_HocPhan
    {
        public int ID { get; set; }
        public int GiangVien_ID { get; set; }
        public int HocPhan_ID { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual HocPhan HocPhan { get; set; }
    }
}
