//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCGD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HocPhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HocPhan()
        {
            this.ChuongTrinh_HocPhan = new HashSet<ChuongTrinh_HocPhan>();
            this.GiangVien_HocPhan = new HashSet<GiangVien_HocPhan>();
            this.PhanCong = new HashSet<PhanCong>();
        }

        [Display(Name = "Mã học phần")]
        [Required(ErrorMessage = "Mã học phần không được bỏ trống!")]
        public string MaHP { get; set; }

        [Display(Name = "Tên học phần")]
        [Required(ErrorMessage = "Tên học phần không được bỏ trống!")]
        public string TenHP { get; set; }

        [Display(Name = "Số tín chỉ")]
        [Required(ErrorMessage = "Số tín chỉ học phần không được bỏ trống!")]
        public int SoTC { get; set; }

        [Display(Name = "Số tín chỉ bắt buộc")]
        public Nullable<int> SoTCBatBuoc { get; set; }

        [Display(Name = "Số tín chỉ tự chọn")]
        public Nullable<int> SoTCTuChon { get; set; }

        [Display(Name = "Số tiết lý thuyết")]
        public Nullable<int> SoTietLT { get; set; }

        [Display(Name = "Số tiết thực hành")]
        public Nullable<int> SoTietTH { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuongTrinh_HocPhan> ChuongTrinh_HocPhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiangVien_HocPhan> GiangVien_HocPhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanCong> PhanCong { get; set; }
    }
}
