//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCGD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCGDEntities : DbContext
    {
        public PCGDEntities()
            : base("name=PCGDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuongTrinh> ChuongTrinh { get; set; }
        public virtual DbSet<ChuongTrinh_HocPhan> ChuongTrinh_HocPhan { get; set; }
        public virtual DbSet<GiangVien> GiangVien { get; set; }
        public virtual DbSet<GiangVien_HocPhan> GiangVien_HocPhan { get; set; }
        public virtual DbSet<HocKi> HocKi { get; set; }
        public virtual DbSet<HocPhan> HocPhan { get; set; }
        public virtual DbSet<Khoa> Khoa { get; set; }
        public virtual DbSet<Lop> Lop { get; set; }
        public virtual DbSet<Nganh> Nganh { get; set; }
        public virtual DbSet<PhanCong> PhanCong { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoan { get; set; }
    }
}
