//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCong
    {
        public int ID { get; set; }
        public int TaiKhoan_ID { get; set; }
        public int HocKi_ID { get; set; }
        public int HocPhan_ID { get; set; }
        public int Lop_ID { get; set; }
        public int GiangVien_ID { get; set; }
        public string GhiChu { get; set; }
        public string LoaiPhong { get; set; }
        public Nullable<int> NhomLT { get; set; }
        public Nullable<int> NhomHT { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual HocKi HocKi { get; set; }
        public virtual HocPhan HocPhan { get; set; }
        public virtual Lop Lop { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
