//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCGD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhanCong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhanCong()
        {
            this.NhiemVu = new HashSet<NhiemVu>();
        }
    
        public long ID { get; set; }
        public int NguoiDung_ID { get; set; }

        [Display(Name = "Học kì")]
        [Required(ErrorMessage = "Học kì không được bỏ trống!")]
        [Range(1, 2, ErrorMessage = "Học kì không hợp lệ")]
        public byte HocKi { get; set; }

        [Display(Name = "Ngày tạo")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date, ErrorMessage = "Định dạng ngày tạo không hợp lệ")]
        [Required(ErrorMessage = "Ngày tạo không được bỏ trống!")]
        public System.DateTime NgayTao { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhiemVu> NhiemVu { get; set; }
    }
    public class ThemNhiemVuModel
    {
        public long PhanCong_ID { get; set; }

        [Display(Name = "Tên giảng viên")]
        [Required(ErrorMessage = "Tên giảng viên không được bỏ trống!")]
        public string TenGV { get; set; }

        [Display(Name = "Tên lớp")]
        [Required(ErrorMessage = "Tên lớp không được bỏ trống!")]
        public string TenLop { get; set; }

        [Display(Name = "Mã học phần")]
        [Required(ErrorMessage = "Mã học phần không được bỏ trống!")]
        public string MaHP { get; set; }

        [Display(Name = "Loại phòng")]
        [Required(ErrorMessage = "Loại phòng không được bỏ trống!")]
        [Range(0, 1, ErrorMessage = "Loại phòng không hợp lệ")]
        public byte LoaiPhong { get; set; }

        [Display(Name = "Nhóm lý thuyết")]
        public Nullable<int> NhomLT { get; set; }

        [Display(Name = "Nhóm thực hành")]
        public Nullable<int> NhomHT { get; set; }

        [Display(Name = "Ghi chú")]
        public string GhiChu { get; set; }
    }
    public class SuaNhiemVuModel
    {
        public long ID { get; set; }
        public long PhanCong_ID { get; set; }

        [Display(Name = "Tên giảng viên")]
        [Required(ErrorMessage = "Tên giảng viên không được bỏ trống!")]
        public string TenGV { get; set; }

        [Display(Name = "Tên lớp")]
        [Required(ErrorMessage = "Tên lớp không được bỏ trống!")]
        public string TenLop { get; set; }

        [Display(Name = "Mã học phần")]
        [Required(ErrorMessage = "Mã học phần không được bỏ trống!")]
        public string MaHP { get; set; }

        [Display(Name = "Loại phòng")]
        [Required(ErrorMessage = "Loại phòng không được bỏ trống!")]
        [Range(0, 1, ErrorMessage = "Loại phòng không hợp lệ")]
        public byte LoaiPhong { get; set; }

        [Display(Name = "Nhóm lý thuyết")]
        public Nullable<int> NhomLT { get; set; }

        [Display(Name = "Nhóm thực hành")]
        public Nullable<int> NhomHT { get; set; }

        [Display(Name = "Ghi chú")]
        public string GhiChu { get; set; }
    }
    public class XoaNhiemVuModel
    {
        public long ID { get; set; }
        public long PhanCong_ID { get; set; }
    }
    public class NhiemVuModel
    {
        public long ID { get; set; }
        public long Lop_ID { get; set; }
        public long PhanCong_ID { get; set; }
        public long HocPhan_ID { get; set; }
        public long GiangVien_ID { get; set; }
        public string TenLop { get; set; }
        public int SoSV { get; set; }
        public string MaHP { get; set; }
        public string TenHP { get; set; }
        public byte LoaiHP { get; set; }
        public int SoTC { get; set; }
        public string TenGV { get; set; }
        public byte LoaiPhong { get; set; }
        public Nullable<int> NhomLT { get; set; }
        public Nullable<int> NhomHT { get; set; }
        public string GhiChu { get; set; }
    }
    public class ViewNhiemVuModel
    {

    }
}
